---
- name: This play is to download the latest war file from nexus
  hosts: localhost
  become: true

  tasks:
     - name: download the war file
       shell: 'curl -u admin:Nexus -L "http://172.31.0.158:8081/service/rest/v1/search/assets/download?sort=version&repository=Devops_project_Release&maven.groupId=com.RavindraDevOpsPro&maven.artifactId=RavindraDevOps&maven.extension=war" -H "accept: application/json" --output /home/ansibleadmin/latest.war'
       args:
         chdir: "/home/ansibleadmin"

- name: Deploy the latest war file to apache tomcat
  hosts: tomcat
  become: true

  tasks:
      - copy:
          src: "{{ item }}"
          dest: "/opt/apache-tomcat-9.0.62/webapps/"
        with_fileglob:
           - "/home/ansibleadmin/*.war"
